name: angular_app
description: Une Web App qui contrôle la maison des chats
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  http: ^0.11.0
  angular_components: '>0.5.0'

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0

